set tabstop=8
set expandtab
set softtabstop=4
set shiftwidth=4
set colorcolumn=120
set autoindent
set ruler
set number
set showmatch
syntax enable
set cursorline 
hi clear CursorLine
hi CursorLine gui=underline cterm=underline
let python_highlight_all=1
au FileType python setlocal formatprg=autopep8\ -
let @a = 'viw"yyo    self.y = y'
